services:
  - type: web
    name: mr-anto-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BROWSERBASE_API_KEY
        sync: false
      - key: BROWSERBASE_PROJECT_ID
        sync: false
